### ISSUE TITLE
Add support for Swift Package Manager

### ISSUE THREAD

**Issue by paweldudek** [AirHelp/Mimus#2]

**Comment by felix91gr** [comment]
Hi! Is there still some interest in this? Because if this would allow Linux support, then I'd like to help :)

**Comment by paweldudek** [comment]
Hey @felix91gr! 

Sorry, I was away for a short May vacation 😊 

Yes, I would love to see support for SPM added. I think that adding support for Linux would require moving [these matchers](https://github.com/AirHelp/Mimus/blob/master/Mimus/Source/Matchers/FoundationMatchers.swift) to a subspec since Foundation classes aren't available there (unless I'm wrong here?), but that sounds like an easy change as well 😉

**Comment by felix91gr** [comment]
Thanks for replying ^^

:thinking: Okay, I'll make a to-do List. This is what I think needs to happen, please tell me what's wrong/missing:

### SPM
* Minmus' code must be grouped under a `Sources` directory.
* Targets for Minmus code must be stated in `Package.swift` (every module is a target, I think)
* Minmus' testing code must be grouped under a `Tests` directory
* Test Targets must be stated in `Package.swift` (usually there's only one test target)
### Compatibility
* This is related to **the matchers you mentioned**: Foundation parts compatibility needs to be checked. The `corelibs-foundation` framework is still incomplete, and we may not have available some pieces that Mimus uses. 
If that's the case, we might have to submit a request for that piece. The `corelibs` folk are really nice people, and are happy to hear what the users of it are looking for because it helps them prioritize their work. It also lets them know that their project is important and that's always good to know :slightly_smiling_face:  
* Syntax compatibility. Specifically some specific Foundation types that can be coerced (`Foo as Bar`) under Darwin but not under Linux. [Here's the current PR on this issue](https://github.com/apple/swift-corelibs-foundation/pull/1526), hopefully it gets merged soon-ish and we get to enjoy hassle free Foundation types usage.

**Comment by paweldudek** [comment]
Fixed by #33, closing!
